### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by sepsol** [DevbookHQ/devbook-palette#13]
I really loved the simplicity and design of this app. Are you deciding on killing it or is it still going to receive updates and new doc additions?

**Comment by mlejva** [comment]
Hello @sepsol, we are currently working on new Devbook and currently don't plan to add any new features to this app.

**Comment by sepsol** [comment]
@mlejva Thanks for the prompt response! Is there any place where I can see the roadmap, track the development, or opt-in for beta releases?

**Comment by mlejva** [comment]
> Is there any place where I can see the roadmap, track the development, or opt-in for beta releases
There isn't. 

The development isn't public yet. We want to share more once we are ready. If things will go well, we should be getting back to our [community](https://discord.gg/ypuZfadw8H) in weeks (I emphasize the "if things will go well"). 

We want to come back once we have something real to share. 

I can only say for now that the first version of new Devbook is about creating technical docs. Mostly for your team and your own projects.
